version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-app-image
        container_name: my-app-container
        ports:
            - "8080:80"
        volumes:
            - .:/app
        command: python src/script.py

